name: SITE_NAME
recipe: drupal8
config:
  webroot: web
  xdebug: true
  # Fix for mysql issue: https://github.com/lando/lando/issues/909
  database: mariadb:10.1
tooling:
  pwd:
    service: appserver
    cmd: pwd
  # Hack to get drupal console to work using "lando drupal"
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
